---
- include: install_tomcat.yml
  tags: packages
  
- name: Update tomcat conf server.xml
  template:
    src: conf_files/tomcat_server_http.xml
    dest: /opt/tomcat/apache-tomcat-{{ tomcat_ver }}/conf/server.xml
  become: true
  notify: enable tomcat startup
